// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: association_contract.proto
// </auto-generated>
// Original file comments:
// *
// Association contract.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.Association {

  #region Events
  public partial class MemberAdded : aelf::IEvent<MemberAdded>
  {
    public global::System.Collections.Generic.IEnumerable<MemberAdded> GetIndexed()
    {
      return new List<MemberAdded>
      {
      new MemberAdded
      {
        OrganizationAddress = OrganizationAddress
      },
      };
    }

    public MemberAdded GetNonIndexed()
    {
      return new MemberAdded
      {
        Member = Member,
      };
    }
  }

  public partial class MemberRemoved : aelf::IEvent<MemberRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<MemberRemoved> GetIndexed()
    {
      return new List<MemberRemoved>
      {
      new MemberRemoved
      {
        OrganizationAddress = OrganizationAddress
      },
      };
    }

    public MemberRemoved GetNonIndexed()
    {
      return new MemberRemoved
      {
        Member = Member,
      };
    }
  }

  public partial class MemberChanged : aelf::IEvent<MemberChanged>
  {
    public global::System.Collections.Generic.IEnumerable<MemberChanged> GetIndexed()
    {
      return new List<MemberChanged>
      {
      new MemberChanged
      {
        OrganizationAddress = OrganizationAddress
      },
      };
    }

    public MemberChanged GetNonIndexed()
    {
      return new MemberChanged
      {
        OldMember = OldMember,
        NewMember = NewMember,
      };
    }
  }

  #endregion
}
#endregion

